spring:
  datasource:
    url: ${DB_JDBC_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    hikari:
      connection-timeout: 2000
      maximum-pool-size: 5
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
    defer-datasource-initialization: true
  profiles:
    include: oauth
    data:
      redis:
        host: ${REDIS_HOST}
        port: ${REDIS_PORT}
    
nutrition :
  key_id : ${NUTRITION_KEY_ID}
  service_id : ${NUTRITION_SERVICE_ID}

jwt:
  token:
    secret-key: ${JWT_SECRET}
  access-token:
    expire-length: 1800000
  refresh-token:
    expire-length: 1209600000

logging:
  level:
    org:
      hibernate:
        type: trace
        stat: debug
        orm:
          jdbc:
            bind: trace
    org.springframework.web.reactive.function.client.ExchangeFunctions: TRACE

cors:
  allowed-origins: "*"
